### ISSUE TITLE
Plzz update the target

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Project-Sloth/ps-signrobbery#12]
Not working with the new qb-target v5.4.0

Plzz update to the new qb-target

**Comment by xxUnknown13xx** [comment]
same here, deleted everything. thought it was a cool script..

**Comment by 1zetsubou** [comment]
yes same here,,not working on qb-target latest ver.

**Comment by MonkeyWhisper** [comment]
This was fixed already
