### ISSUE TITLE
qb-target

### ISSUE THREAD

**Issue by Pardison** [Project-Sloth/ps-signrobbery#13]
new qb-target export cant 3rd eye the signs to rob them

**Comment by MonkeyWhisper** [comment]
> new qb-target export cant 3rd eye the signs to rob them

It works fine. Just tested it, a fresh copy of it. 
![image](https://user-images.githubusercontent.com/82112471/200967059-3fb1b14b-2512-4dd0-b81f-e5b5acb1a40c.png)

If you want us to look at this, provide video or errors.
