### ISSUE TITLE
dosnt take the sign 

### ISSUE THREAD

**Issue by Gametake** [Project-Sloth/ps-signrobbery#17]
![image](https://github.com/Project-Sloth/ps-signrobbery/assets/102847957/eb8394a6-0c6a-47fd-abc3-372ebd4f2f98)
After the minigame and progress bar dosnt make anything

**Comment by TheRealSago** [comment]
I have the exact same issue, just followed instructions. 
Worked fine on the Testserver 2 Months ago.

**Comment by MixicalScripts** [comment]
Having the same issue with this script too!

**Comment by MonkeyWhisper** [comment]
User error

**Comment by VelmaJinks** [comment]
Within four days there are at least five people having the exact same error and they've all made the same "user error"? With no insight into what that user error is or help in correcting it?

**Comment by MonkeyWhisper** [comment]
> Within four days there are at least five people having the exact same error and they've all made the same "user error"? With no insight into what that user error is or help in correcting it?

Fix it yourself, open source. Stop spamming this with your bullshit
