### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by skrimxyz** [Project-Sloth/ps-signrobbery#2]
When you steal a sign it's not synced with other players

**Comment by MonkeyWhisper** [comment]
It is, other people see it

**Comment by JoeSzymkowiczFiveM** [comment]
If you can provide more information on steps to reliably recreate the issue, it would be appreciated.

**Comment by zWyzzzzz** [comment]
https://streamable.com/fgg529

**Comment by JoeSzymkowiczFiveM** [comment]
Attempted fix with ad09b84. Please retest.

**Comment by skrimxyz** [comment]
The issue was fixed
